name: Triggered
on:
  workflow_run:
    workflows: [Main]
    types: [completed]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print trigger information
        run: |
          echo 'Triggered by: ${{ github.event.workflow.name }} (${{ github.event.workflow_run.html_url }})' >> $GITHUB_STEP_SUMMARY
          echo 'Commit "${{ github.event.workflow_run.head_commit.message }}" by ${{ github.event.workflow_run.head_commit.author.email }} / ${{ github.event.workflow_run.head_commit.committer.email }}' >> $GITHUB_STEP_SUMMARY
