name: Triggered
on:
  workflow_run:
    workflows: [Main]
    types: [completed]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print debug information
        run: |
          echo "# Workflow" >> $GITHUB_STEP_SUMMARY
          echo <<<"EOF"
          '```json
          ${{ toJSON(github.event.workflow) }}
          ```'
          EOF >> $GITHUB_STEP_SUMMARY
          echo "# Workflow run" >> $GITHUB_STEP_SUMMARY
          echo <<<"EOF"
          '```json
          ${{ toJSON(github.event.workflow_run) }}
          ```'
          EOF>> $GITHUB_STEP_SUMMARY
